### ISSUE TITLE
Chrome browser

### ISSUE THREAD

**Issue by trikon** [iliakan/javascript-book#4]
Не генерится дерево навигации в Chrome(nav.html). Вроде как апплет отрабатывает но нет результата. 
ЗЫ Сори если не туда куда нужно отписал. Новичок в github-e...

**Comment by trikon** [comment]
Моя ошибка, запускал все локально (XMLHttpRequest cannot load /javascript-book/en/metadata.applet.json. Cross origin requests are only supported for HTTP.) Запустил на локальном сервере и все ок.

**Comment by iliakan** [comment]
Привет!

А ты просто читать хочешь или редактировать тоже?

---

С уважением,
Илья Кантор

14 июня 2011 г. 14:36 пользователь andry308
reply@reply.github.com
написал:

**Comment by iliakan** [comment]
P.S. Для Chrome нужен флаг --allow-file-access-from-files или чтото
вроде того, @see readme.

---

С уважением,
Илья Кантор

14 июня 2011 г. 15:08 пользователь Ilia Kantor iliakan@gmail.com написал:

**Comment by trikon** [comment]
Привет! Пока читать, но по свободе можно заняться и переводом.
